---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn.yaml
  - bitnami.yaml
  - bjw-s.yaml
  - core-dns.yaml
  - external-dns.yaml
  - grafana.yaml
  - home-ops.yaml
  - ingress-nginx.yaml
  - node-feature-discovery.yaml
  - prometheus-community.yaml
  - vector.yaml
