---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esp-home-config
  namespace: house
  labels:
    k10.kasten.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esp-home-cache
  namespace: house
  labels:
    k10.kasten.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi