---
collections:
  - name: community.general
    version: 11.4.1
  - name: community.docker
    version: 3.13.10
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 1.9.5

roles:
  - src: xanmanning.k3s
    version: v3.6.1