---
collections:
  - name: community.general
    version: 12.3.0
  - name: community.docker
    version: 5.0.6
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 2.2.7

roles:
  - src: xanmanning.k3s
    version: v3.6.2