---
collections:
  - name: community.general
    version: 9.5.12
  - name: community.docker
    version: 3.13.9
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 1.9.4

roles:
  - src: xanmanning.k3s
    version: v3.6.1