---
collections:
  - name: community.general
    version: 9.5.13
  - name: community.docker
    version: 3.13.10
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 2.2.7

roles:
  - src: xanmanning.k3s
    version: v3.6.2