---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt
  namespace: house
  labels:
    k10.kasten.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
    volumeName: pvc-546ec277-77f7-43bc-ae56-a544f16574d7
